export const SECURITY_FEATURES = [
  { key: "adaptive_thresholds", name: "Adaptive thresholds", description: "Tune strict, balanced, and permissive thresholds from observed traffic." },
  { key: "shadow_mode", name: "Shadow mode", description: "Log would-block decisions before enforcing them." },
  { key: "replay_protection", name: "Replay protection", description: "Consume challenge tokens once and expire them quickly." },
  { key: "origin_allowlist", name: "Origin allowlist", description: "Reject browser challenges from unapproved origins." },
  { key: "ip_controls", name: "IP controls", description: "Maintain project IP allow and block lists." },
  { key: "rate_limits", name: "Rate limits", description: "Limit verification, signup, login, and challenge abuse." },
  { key: "risk_reasons", name: "Risk reasons", description: "Explain the high-level signals behind a score without storing content." },
  { key: "request_correlation", name: "Request correlation", description: "Trace challenge, verification, and support events safely." },
  { key: "retention_controls", name: "Retention controls", description: "Set bounded deletion windows for security telemetry." },
  { key: "privacy_modes", name: "Privacy modes", description: "Choose minimal, standard, or strict telemetry collection." },
  { key: "consent_gate", name: "Consent gate", description: "Allow customers to require their own consent before telemetry." },
  { key: "accessibility_review", name: "Accessibility review path", description: "Route borderline users to review or alternate challenge flows." },
  { key: "webhook_alerts", name: "Webhook alerts", description: "Send selected security events to a customer HTTPS endpoint." },
  { key: "secret_rotation", name: "Secret rotation", description: "Rotate project secrets with a bounded migration window." },
  { key: "fail_open_policy", name: "Fail-open policy", description: "Choose availability behavior for internal control-plane outages." },
  { key: "audit_log", name: "Security audit log", description: "Record policy, key, access, and administrative changes." },
  { key: "country_policy", name: "Country policy", description: "Support explicit country allow and block policy inputs." },
  { key: "device_signals", name: "Device automation signals", description: "Use webdriver and capability signals as one component, never alone." },
  { key: "network_signals", name: "Network signals", description: "Use coarse connection hints without collecting payload content." },
  { key: "data_export_delete", name: "Export and delete controls", description: "Support verified customer requests for data access and deletion." },
  { key: "session_velocity", name: "Session velocity", description: "Detect unusually fast navigation and repeated actions in one session." },
  { key: "token_age_policy", name: "Token age policy", description: "Set a shorter maximum token age for sensitive actions." },
  { key: "per_endpoint_policy", name: "Per-endpoint policy", description: "Use different thresholds for signup, login, checkout, and comments." },
  { key: "per_account_limits", name: "Per-account limits", description: "Apply abuse limits to an account or tenant in addition to IP limits." },
  { key: "per_key_limits", name: "Per-key limits", description: "Isolate traffic quotas for each public project key." },
  { key: "reputation_cache", name: "Reputation cache", description: "Cache short-lived provider results without storing raw provider payloads." },
  { key: "provider_timeout", name: "Provider timeout", description: "Bound optional provider latency so detection cannot hang a customer request." },
  { key: "provider_circuit_breaker", name: "Provider circuit breaker", description: "Temporarily stop calling an unhealthy optional provider." },
  { key: "provider_data_minimization", name: "Provider data minimization", description: "Send only the minimum event fields selected by the customer." },
  { key: "webhook_retry_policy", name: "Webhook retry policy", description: "Retry customer alerts with bounded exponential backoff." },
  { key: "webhook_signatures", name: "Webhook signatures", description: "Sign outbound event payloads and support timestamp checks." },
  { key: "webhook_replay_protection", name: "Webhook replay protection", description: "Reject duplicate inbound or outbound event deliveries." },
  { key: "alert_deduplication", name: "Alert deduplication", description: "Collapse repeated alerts into a useful incident summary." },
  { key: "incident_mode", name: "Incident mode", description: "Apply a temporary emergency policy with an expiry time." },
  { key: "maintenance_mode", name: "Maintenance mode", description: "Return an explicit degraded response during planned maintenance." },
  { key: "policy_approval", name: "Policy approval", description: "Require a second operator to approve high-impact policy changes." },
  { key: "policy_rollback", name: "Policy rollback", description: "Restore the last known-good policy version quickly." },
  { key: "policy_dry_run", name: "Policy dry run", description: "Evaluate a policy against recent traffic without changing decisions." },
  { key: "score_calibration", name: "Score calibration", description: "Compare score bands against confirmed outcomes and false positives." },
  { key: "false_positive_feedback", name: "False-positive feedback", description: "Collect verified customer feedback on blocked legitimate requests." },
  { key: "review_queue", name: "Review queue", description: "Queue borderline requests for customer review instead of immediate denial." },
  { key: "appeal_tokens", name: "Appeal tokens", description: "Issue a short-lived retry path after a verified human appeal." },
  { key: "accessibility_headers", name: "Accessibility headers", description: "Expose clear response guidance for alternate accessible flows." },
  { key: "privacy_redaction", name: "Privacy redaction", description: "Remove optional identifiers from logs and support exports." },
  { key: "regional_retention", name: "Regional retention", description: "Configure retention policy by deployment region where supported." },
  { key: "customer_export", name: "Customer security export", description: "Export project security events in a portable format." },
  { key: "admin_mfa_required", name: "Admin MFA required", description: "Require MFA before sensitive dashboard operations." },
  { key: "admin_ip_allowlist", name: "Admin IP allowlist", description: "Restrict administrative actions to trusted network ranges." },
  { key: "break_glass_audit", name: "Break-glass audit", description: "Audit emergency overrides with reason, actor, and expiry." },
  { key: "security_scorecard", name: "Security scorecard", description: "Show configuration coverage and recommended hardening actions." },
] as const;

export type SecurityFeatureKey = (typeof SECURITY_FEATURES)[number]["key"];
export const isSecurityFeatureKey = (value: string): value is SecurityFeatureKey => SECURITY_FEATURES.some((feature) => feature.key === value);
