"use client";
import { useEffect, useState } from "react";
import { DashboardShell } from "@/components/layouts/dashboard-shell";
import { toast } from "@/components/toast";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
type Project = { id: string; name: string };
type SecurityData = { projects: Project[]; hooks: Array<{ id: string; endpoint_url: string; active: boolean }>; events: Array<{ id: string; event_type: string; created_at: string }>; alerts?: Array<{ id: string; user_agent?: string; created_at: string }>; mfa?: { status?: string } | null };
const thresholds: Record<string, number> = { strict: 30, balanced: 50, permissive: 80 };

export default function SecurityCenter() {
  const [data, setData] = useState<SecurityData | null>(null);
  const [projectId, setProjectId] = useState("");
  const [profile, setProfile] = useState("balanced");
  const [policyAction, setPolicyAction] = useState("shadow");
  const [webhook, setWebhook] = useState("");
  const load = async () => { const { data: auth } = await supabase.auth.getSession(); const response = await fetch("/api/security-center", { headers: { Authorization: `Bearer ${auth.session?.access_token || ""}` } }); if (response.ok) { const body = await response.json() as SecurityData; setData(body); setProjectId((current) => current || body.projects?.[0]?.id || ""); } };
  // The dashboard must hydrate from the authenticated API after mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, []);
  const call = async (body: Record<string, unknown>) => { const { data: auth } = await supabase.auth.getSession(); const response = await fetch("/api/security-center", { method: "POST", headers: { Authorization: `Bearer ${auth.session?.access_token || ""}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) return toast("error", result.error || "Action failed"); toast("success", result.warning || "Saved"); await load(); };
  if (!data) return <DashboardShell userType="user"><div className="min-h-[400px] animate-pulse rounded-2xl bg-slate-900" /></DashboardShell>;
  return <DashboardShell userType="user"><div className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-400">Security control plane</p><h1 className="mt-2 text-3xl font-bold text-white">Security Center</h1><p className="mt-2 text-slate-400">Roll out detection gradually, keep decisions server-side, and monitor false positives.</p></header>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">Staged policy rollout</h2><p className="mt-2 text-sm leading-relaxed text-slate-400">Start with shadow logging, review real traffic for several days, then enable blocking. Mouse movement is never the only signal, and borderline users should have an accessible alternative.</p><div className="mt-4 grid gap-3 sm:grid-cols-4"><select value={projectId} onChange={(e) => setProjectId(e.target.value)} aria-label="Project" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white">{data.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><select value={profile} onChange={(e) => setProfile(e.target.value)} aria-label="Sensitivity profile" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white"><option value="permissive">Permissive · 80+</option><option value="balanced">Balanced · 50+</option><option value="strict">Strict · 30+</option></select><select value={policyAction} onChange={(e) => setPolicyAction(e.target.value)} aria-label="Policy action" className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white"><option value="shadow">Shadow log</option><option value="challenge">Challenge</option><option value="block">Block</option></select><button onClick={() => call({ action: "save-policy", project_id: projectId, profile, threshold: thresholds[profile] || 50, policy_action: policyAction, challenge_type: "behavioral" })} className="rounded-xl bg-blue-600 px-4 py-3 text-sm text-white">Publish policy</button></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">Key lifecycle</h2><p className="mt-2 text-sm text-slate-400">Rotate keys through the dashboard and keep a short grace window for migration.</p><div className="mt-4 space-y-3">{data.projects.map((project) => <div key={project.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-950 p-4"><span className="text-sm text-white">{project.name}</span><span className="flex gap-2"><button onClick={() => call({ action: "rotate-key", project_id: project.id })} className="rounded-lg border border-amber-500/30 px-3 py-2 text-xs text-amber-300">Rotate once</button><button onClick={() => call({ action: "schedule-rotation", project_id: project.id, interval_days: 30, grace_hours: 24 })} className="rounded-lg border border-blue-500/30 px-3 py-2 text-xs text-blue-300">Schedule</button></span></div>)}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">Webhook subscriptions</h2><div className="mt-4 flex gap-2"><input value={webhook} onChange={(e) => setWebhook(e.target.value)} placeholder="https://your-app.com/botshield" aria-label="Webhook HTTPS URL" className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white" /><button onClick={() => call({ action: "create-webhook", endpoint_url: webhook })} className="rounded-xl bg-blue-600 px-4 py-3 text-sm text-white">Add</button></div><div className="mt-4 space-y-2">{data.hooks.map((hook) => <p key={hook.id} className="rounded-lg bg-slate-950 p-3 text-xs text-slate-400">{hook.endpoint_url} · {hook.active ? "active" : "paused"}</p>)}</div></div></section>
    <section className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-6"><h2 className="text-lg font-semibold text-white">Accessibility and privacy checklist</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-relaxed text-slate-400"><li>Do not require mouse movement; keyboard-only and assistive-technology users need a review or alternate challenge path.</li><li>Use exact HTTPS origins and keep secret keys off the client.</li><li>Review shadow-mode scores before enabling block mode.</li><li>Hash IP addresses and set a retention period for security analytics.</li></ul></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">Security activity</h2><div className="mt-4 divide-y divide-slate-800">{data.events.length ? data.events.map((event) => <div key={event.id} className="flex justify-between gap-4 py-3 text-sm"><span className="text-slate-300">{event.event_type}</span><time className="text-xs text-slate-600">{new Date(event.created_at).toLocaleString()}</time></div>) : <p className="text-sm text-slate-500">No security events recorded yet.</p>}</div></section>
  </div></DashboardShell>;
}
