"use client";
import { useEffect, useState } from "react";
import { DashboardShell } from "@/components/layouts/dashboard-shell";
import { toast } from "@/components/toast";
import { createClient } from "@supabase/supabase-js";
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
export default function SecurityCenter() {
  const [data, setData] = useState<any>(null); const [projectId, setProjectId] = useState(""); const [profile, setProfile] = useState("balanced"); const [policyAction, setPolicyAction] = useState("block"); const [webhook, setWebhook] = useState("");
  const load = async () => { const { data: auth } = await supabase.auth.getSession(); const response = await fetch("/api/security-center", { headers: { Authorization: `Bearer ${auth.session?.access_token || ""}` } }); if (response.ok) { const body = await response.json(); setData(body); setProjectId((current) => current || body.projects?.[0]?.id || ""); } };
  useEffect(() => { load(); }, []);
  const call = async (body: Record<string, unknown>) => { const { data: auth } = await supabase.auth.getSession(); const response = await fetch("/api/security-center", { method: "POST", headers: { Authorization: `Bearer ${auth.session?.access_token || ""}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) return toast("error", result.error || "Action failed"); toast("success", result.warning || "Saved"); await load(); };
  if (!data) return <DashboardShell userType="user"><div className="min-h-[400px] animate-pulse rounded-2xl bg-slate-900" /></DashboardShell>;
  return <DashboardShell userType="user"><div className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-400">Security control plane</p><h1 className="mt-2 text-3xl font-bold text-white">Security Center</h1><p className="mt-2 text-slate-400">Manage policies, keys, webhooks, and account security from one place.</p></header>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">Policy builder</h2><div className="mt-4 grid gap-3 sm:grid-cols-4"><select value={projectId} onChange={(e) => setProjectId(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white">{data.projects.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={profile} onChange={(e) => setProfile(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white"><option value="permissive">Permissive</option><option value="balanced">Balanced</option><option value="strict">Strict</option></select><select value={policyAction} onChange={(e) => setPolicyAction(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white"><option value="block">Block</option><option value="challenge">Challenge</option><option value="shadow">Shadow log</option></select><button onClick={() => call({ action: "save-policy", project_id: projectId, profile, threshold: 70, policy_action: policyAction, challenge_type: "behavioral" })} className="rounded-xl bg-blue-600 px-4 py-3 text-sm text-white">Publish policy</button></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">Key lifecycle</h2><p className="mt-2 text-sm text-slate-400">Rotate once or schedule a 30-day rotation with a 24-hour grace window.</p><div className="mt-4 space-y-3">{data.projects.map((p: any) => <div key={p.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-950 p-4"><span className="text-sm text-white">{p.name}</span><span className="flex gap-2"><button onClick={() => call({ action: "rotate-key", project_id: p.id })} className="rounded-lg border border-amber-500/30 px-3 py-2 text-xs text-amber-300">Rotate once</button><button onClick={() => call({ action: "schedule-rotation", project_id: p.id, interval_days: 30, grace_hours: 24 })} className="rounded-lg border border-blue-500/30 px-3 py-2 text-xs text-blue-300">Schedule</button></span></div>)}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">Webhook subscriptions</h2><div className="mt-4 flex gap-2"><input value={webhook} onChange={(e) => setWebhook(e.target.value)} placeholder="https://your-app.com/botshield" className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-3 py-3 text-sm text-white" /><button onClick={() => call({ action: "create-webhook", endpoint_url: webhook })} className="rounded-xl bg-blue-600 px-4 py-3 text-sm text-white">Add</button></div><div className="mt-4 space-y-2">{data.hooks.map((h: any) => <p key={h.id} className="rounded-lg bg-slate-950 p-3 text-xs text-slate-400">{h.endpoint_url} · {h.active ? "active" : "paused"}</p>)}</div></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">MFA enrollment</h2><p className="mt-2 text-sm text-slate-400">Current status: {data.mfa?.status || "not enrolled"}</p><button onClick={() => call({ action: "enroll-mfa", method: "totp" })} className="mt-4 rounded-xl border border-violet-500/30 px-4 py-3 text-sm text-violet-300">Start TOTP enrollment</button></div><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">Login alerts</h2><div className="mt-3 space-y-2">{data.alerts?.length ? data.alerts.slice(0, 5).map((a: any) => <div key={a.id} className="rounded-xl bg-slate-950 p-3 text-xs text-slate-400">{a.user_agent || "Unknown device"} · {new Date(a.created_at).toLocaleString()}</div>) : <p className="text-sm text-slate-500">No login alerts recorded.</p>}</div></div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><h2 className="text-xl font-semibold text-white">Security activity</h2><div className="mt-4 divide-y divide-slate-800">{data.events.length ? data.events.map((e: any) => <div key={e.id} className="flex justify-between gap-4 py-3 text-sm"><span className="text-slate-300">{e.event_type}</span><time className="text-xs text-slate-600">{new Date(e.created_at).toLocaleString()}</time></div>) : <p className="text-sm text-slate-500">No security events recorded yet.</p>}</div></section>
  </div></DashboardShell>;
}
